// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Reservation struct {
	ID              int32
	Token           string
	Name            string
	Email           string
	Status          string
	TableNo         sql.NullInt32
	TimeSlotID      sql.NullInt32
	ReservationDate time.Time
	CreatedAt       sql.NullTime
}

type Table struct {
	ID        int32
	Capacity  int32
	CreatedAt sql.NullTime
}

type TimeSlot struct {
	ID        int32
	StartTime time.Time
	EndTime   time.Time
}
