// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Subscription struct {
	ID        int32
	Email     string
	Status    bool
	StartedAt sql.NullTime
	EndedAt   sql.NullTime
}
