// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscription.sql

package db

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscription( email )
VALUES ( $1 )
`

func (q *Queries) CreateSubscription(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, createSubscription, email)
	return err
}

const listSubscriptionEmail = `-- name: ListSubscriptionEmail :many
SELECT email FROM subscription
WHERE status = true
`

func (q *Queries) ListSubscriptionEmail(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSubscriptionEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
