// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.20.3
// source: mail-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To              string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Token           string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Type            string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ReservationDate string `protobuf:"bytes,5,opt,name=reservationDate,proto3" json:"reservationDate,omitempty"`
	TimeSlot        string `protobuf:"bytes,6,opt,name=timeSlot,proto3" json:"timeSlot,omitempty"`
}

func (x *ReservationMail) Reset() {
	*x = ReservationMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservationMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationMail) ProtoMessage() {}

func (x *ReservationMail) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationMail.ProtoReflect.Descriptor instead.
func (*ReservationMail) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReservationMail) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReservationMail) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReservationMail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReservationMail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReservationMail) GetReservationDate() string {
	if x != nil {
		return x.ReservationDate
	}
	return ""
}

func (x *ReservationMail) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

type SubscriptionMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To      []string `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Subject string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body    string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SubscriptionMail) Reset() {
	*x = SubscriptionMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionMail) ProtoMessage() {}

func (x *SubscriptionMail) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionMail.ProtoReflect.Descriptor instead.
func (*SubscriptionMail) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionMail) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SubscriptionMail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubscriptionMail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendReservationMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservationMailEntry *ReservationMail `protobuf:"bytes,1,opt,name=reservationMailEntry,proto3" json:"reservationMailEntry,omitempty"`
}

func (x *SendReservationMailRequest) Reset() {
	*x = SendReservationMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReservationMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReservationMailRequest) ProtoMessage() {}

func (x *SendReservationMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReservationMailRequest.ProtoReflect.Descriptor instead.
func (*SendReservationMailRequest) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendReservationMailRequest) GetReservationMailEntry() *ReservationMail {
	if x != nil {
		return x.ReservationMailEntry
	}
	return nil
}

type SendSubscriptionMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionMailEntry *SubscriptionMail `protobuf:"bytes,1,opt,name=subscriptionMailEntry,proto3" json:"subscriptionMailEntry,omitempty"`
}

func (x *SendSubscriptionMailRequest) Reset() {
	*x = SendSubscriptionMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSubscriptionMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSubscriptionMailRequest) ProtoMessage() {}

func (x *SendSubscriptionMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSubscriptionMailRequest.ProtoReflect.Descriptor instead.
func (*SendSubscriptionMailRequest) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendSubscriptionMailRequest) GetSubscriptionMailEntry() *SubscriptionMail {
	if x != nil {
		return x.SubscriptionMailEntry
	}
	return nil
}

type SendMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendMailResponse) Reset() {
	*x = SendMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailResponse) ProtoMessage() {}

func (x *SendMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailResponse.ProtoReflect.Descriptor instead.
func (*SendMailResponse) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendMailResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *SendMailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mail_service_proto protoreflect.FileDescriptor

var file_mail_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x50, 0x0a, 0x10, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x6f, 0x0a, 0x1a,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x14, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x14, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x73, 0x0a,
	0x1b, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x15,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61,
	0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x15, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x22, 0x42, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd1, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x2e,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6c, 0x12,
	0x29, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x61, 0x69,
	0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mail_service_proto_rawDescOnce sync.Once
	file_mail_service_proto_rawDescData = file_mail_service_proto_rawDesc
)

func file_mail_service_proto_rawDescGZIP() []byte {
	file_mail_service_proto_rawDescOnce.Do(func() {
		file_mail_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_mail_service_proto_rawDescData)
	})
	return file_mail_service_proto_rawDescData
}

var file_mail_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mail_service_proto_goTypes = []interface{}{
	(*ReservationMail)(nil),             // 0: mail_service.ReservationMail
	(*SubscriptionMail)(nil),            // 1: mail_service.SubscriptionMail
	(*SendReservationMailRequest)(nil),  // 2: mail_service.SendReservationMailRequest
	(*SendSubscriptionMailRequest)(nil), // 3: mail_service.SendSubscriptionMailRequest
	(*SendMailResponse)(nil),            // 4: mail_service.SendMailResponse
}
var file_mail_service_proto_depIdxs = []int32{
	0, // 0: mail_service.SendReservationMailRequest.reservationMailEntry:type_name -> mail_service.ReservationMail
	1, // 1: mail_service.SendSubscriptionMailRequest.subscriptionMailEntry:type_name -> mail_service.SubscriptionMail
	2, // 2: mail_service.MailService.SendReservationMail:input_type -> mail_service.SendReservationMailRequest
	3, // 3: mail_service.MailService.SendSubscriptionMail:input_type -> mail_service.SendSubscriptionMailRequest
	4, // 4: mail_service.MailService.SendReservationMail:output_type -> mail_service.SendMailResponse
	4, // 5: mail_service.MailService.SendSubscriptionMail:output_type -> mail_service.SendMailResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mail_service_proto_init() }
func file_mail_service_proto_init() {
	if File_mail_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mail_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservationMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReservationMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSubscriptionMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mail_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mail_service_proto_goTypes,
		DependencyIndexes: file_mail_service_proto_depIdxs,
		MessageInfos:      file_mail_service_proto_msgTypes,
	}.Build()
	File_mail_service_proto = out.File
	file_mail_service_proto_rawDesc = nil
	file_mail_service_proto_goTypes = nil
	file_mail_service_proto_depIdxs = nil
}
